version: '3.5'

services:
   php:
     build:
       context: .
       args:
         user: '1000'
         uid: '1000'
     container_name: php
     tty: true
     volumes:
       - ./:/var/www/html
     networks:
       - php_net

   nginx:
     image: nginx:stable-alpine
     container_name: nginx
     tty: true
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./:/var/www/html
       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
       - php
     networks:
       - php_net
networks:
  php_net: